<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class GenericModel extends Model
{
    public function __call($method, $parameters)
    {
        if (str_starts_with($method, 'get')) {
            $attribute = Str::snake(str_replace('get', '', $method));
            if ($this->hasAttribute($attribute)) {
                return $this->getAttribute($attribute);
            }
        }

        return parent::__call($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function hasAttribute(string $attribute): bool
    {
        return isset($this->attributes[$attribute]);
    }

    public function getId() : int
    {
        return (int)$this->getAttribute($this->primaryKey);
    }
}
